apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "payment-processing-service.fullname" . }}-config
  labels:
    {{- include "payment-processing-service.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap }}
  {{ $key }}: |
    {{- $value | nindent 4 }}
  {{- end }}