name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: payments_test
          POSTGRES_USER: payments
          POSTGRES_PASSWORD: payments123
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h localhost -p 5432 -U payments; do
          echo "Waiting for PostgreSQL..."
          sleep 1
        done
        echo "PostgreSQL is ready!"
    
    - name: Run tests
      run: ./gradlew test
      env:
        DB_URL: jdbc:postgresql://localhost:5432/payments_test
        DB_USERNAME: payments
        DB_PASSWORD: payments123
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          **/build/reports/tests/
          **/build/test-results/